exclude: "node_modules|.git"
default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
        files: "flow.*"
        exclude: ".*json$|.*txt$|.*csv|.*md|.*svg"
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
        # exclude: |
        #   (?x)^(
        #       frontend/.*tsconfig.*\.json
        #   )$
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        name: "Run ruff linter and apply fixes"
        args: ["--fix"]

      - id: ruff-format
        name: "Format Python code"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ["--quiet"]
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
              otto/public/dist/.*|
              cypress/.*|
              .*node_modules.*|
              .*boilerplate.*|
              otto/templates/includes/.*|
              otto/public/js/lib/.*
          )$

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false